### ISSUE TITLE
Improve up/down vote flow

### ISSUE THREAD

**Issue by sivaprasadreddy** [sivaprasadreddy/techbuzz#48]
Currently, after the user up/down votes, the current page is refreshed. Reloading the entire page is unnecessary just to reflect the vote count. 

Maybe using HTMX/AlpineJS to ajaxify this behaviour is better.

**Comment by adityachaudhari** [comment]
Hi @sivaprasadreddy 
I am planning to work on this task. 
As want to debug the spring-boot app did below steps.

In my local, went to techbuzz  
run mvn clean install.

While doing mvn clean install i am getting below error.
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/11736797/236664791-46e55709-c23d-4e03-8720-0c011281ef93.png">


Initially i was on java 18 then switched to the java 17 but still see the same error. 
My current Java version is "openjdk version "17.0.7" 2023-04-18 LTS"

Could you please help me figure out what is going wrong?

My goal is to run project locally and enable debug so that i can debug and contribute on the tasks.

Please let me know if you need additional information to help me out.

**Comment by adityachaudhari** [comment]
Hi @sivaprasadreddy  
Please ignore my above comment it was due to my java_version i was not able to do mvn install.
But now facing another issue .

I am trying to  start application locally to debug. Not sure if "$ ./run.sh start"  will enable me to debug hence trying other way mentioned by you in the document which is 
$ ./run.sh start_infra
$ ./mvnw spring-boot:run

but when i do ./mvnw spring-boot:run , it says my DB is not up. seems some problem when i initialize DB with "./run.sh start_infra.
Before i jump to check what is wrong there I would like to know from you the exact steps by which i will be able to debug the java files.

Could you please help me with the exact steps to debug application locally?

many thanks
Aditya C

**Comment by sivaprasadreddy** [comment]
@adityachaudhari  To debug the application from IDE, you can simply run `TestTechBuzzApplication.java` under `src/test/java` from IDE. This will automatically start the required containers in docker.

**Comment by sivaprasadreddy** [comment]
I have the following docker and docker-compose versions and `./run.sh start` is working fine for me.

```
$ docker -v
Docker version 23.0.1-rd, build 393499b

$ docker compose version
Docker Compose version v2.17.3
```

**Comment by adityachaudhari** [comment]
@sivaprasadreddy 
Wow, with just a TestTechBuzzApplication execution it start's the docker containers its magic for me.

My docker versions was the problem, updated my docker which solved my problem.

Able to debug just by executing TestTechBuzzApplication.
Thanks for quick response.

**Comment by sivaprasadreddy** [comment]
Implemented by @adityachaudhari
